In [54]:
import pandas as pd
import numpy as np

In [55]:
df_raw = pd.read_csv("datasets/nordkaffe_ordrar.csv")

df_raw.head()

,order_id,kund_id,order_datum,produkt,kategori,antal,pris_st,kanal,status
0,ORD-001,K001,2024-01-15,Espresso Blend,Kaffe,2,189.00,online,levererad
1,ORD-002,K003,2024-01-16,Lungo Klassisk,kaffe,1,169.00,butik,levererad
2,ORD-003,K002,17/01/2024,Cappuccino Mix,Kaffe,3,199.00,Online,levererad
3,ORD-004,K005,2024-01-18,Kaffekvarn Pro,Tillbehör,1,899.00,online,LEVERERAD
4,ORD-005,K001,2024-01-20,Espresso Blend,Kaffe,1,189.00,butik,levererad

In [56]:
df_raw.sample(10)

,order_id,kund_id,order_datum,produkt,kategori,antal,pris_st,kanal,status
1,ORD-002,K003,2024-01-16,Lungo Klassisk,kaffe,1,169.00,butik,levererad
27,ORD-028,K019,2024-03-18,Cappuccino Mix,KAFFE,2,199.00,Online,levererad
29,ORD-030,K020,22/03/2024,Termos Deluxe,tillbehör,1,329.00,online,RETURNERAD
35,ORD-036,K023,08/04/2024,Cappuccino Mix,Kaffe,1,199.00,online,levererad
30,ORD-031,K013,2024-03-25,Espresso Blend,Kaffe,2,189.00,Butik,levererad
9,ORD-010,K007,30/01/2024,Kaffebönor Dark,KAFFE,1,219.00,Online,levererad
24,ORD-025,K002,2024-03-10,Kaffebönor Dark,kaffe,1,219.00,Butik,LEVERERAD
19,ORD-020,K015,25/02/2024,Cappuccino Mix,Kaffe,1,199.00,butik,levererad
25,ORD-026,K018,2024-03-12,Espresso Blend,Kaffe,1,189.00,online,levererad
21,ORD-022,K016,2024-03-02,Filterkanna Glas,tillbehör,1,249.00,butik,returnerad

In [57]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     40 non-null     str
 1   kund_id      40 non-null     str
 2   order_datum  40 non-null     str
 3   produkt      40 non-null     str
 4   kategori     40 non-null     str
 5   antal        40 non-null     int64
 6   pris_st      40 non-null     str
 7   kanal        40 non-null     str
 8   status       40 non-null     str
dtypes: int64(1), str(8)
memory usage: 2.9 KB

In [58]:
df_raw["kund_id"].nunique()

25

In [59]:
def clean_categories(df):

    df["kategori"] = df["kategori"].str.strip().str.lower()

    return df

In [60]:
df_raw["kanal"].value_counts()

kanal
online        13
butik         10
Online         6
Butik          5
  butik        2
  Online       1
  online       1
  butik        1
  Online       1
Name: count, dtype: int64

In [61]:
def clean_channel(df):

    df["kanal"] = df["kanal"].str.strip().str.lower()

    return df

In [62]:
df_raw["status"].value_counts()

status
levererad     30
LEVERERAD      5
returnerad     4
RETURNERAD     1
Name: count, dtype: int64

In [63]:
def clean_status(df):
    df["status"] = df["status"].str.strip().str.lower()

    return df

In [64]:
df_raw["pris_st"].value_counts()

pris_st
189.00      10
169.00       6
199.00       5
179.00       5
219.00       4
899.00       2
1 299.00     2
449.00       2
329.00       2
599.00       1
249.00       1
Name: count, dtype: int64

In [65]:
def clean_order_price(df):

    df["pris_st"] = df["pris_st"].str.replace("kr", "").str.replace(" ", "").astype(float)

    return df

In [66]:
df_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     40 non-null     str
 1   kund_id      40 non-null     str
 2   order_datum  40 non-null     datetime64[us]
 3   produkt      40 non-null     str
 4   kategori     40 non-null     str
 5   antal        40 non-null     int64
 6   pris_st      40 non-null     str
 7   kanal        40 non-null     str
 8   status       40 non-null     str
 9   order_month  40 non-null     int32
 10  order_day    40 non-null     str
dtypes: datetime64[us](1), int32(1), int64(1), str(8)
memory usage: 3.4 KB

In [67]:
def clean_date(df):

    df["order_datum"] = pd.to_datetime(df["order_datum"], dayfirst=True, errors="coerce", format="mixed")

    return df

In [68]:
def add_order_total(df):
    
    df["order_total"] = df["pris_st"] * df["antal"]

    return df

In [69]:
def add_time_features(df):

    df["order_month"] = df["order_datum"].dt.month
    df["order_day"] = df["order_datum"].dt.day_name()

    return df

In [88]:
def transform_orders(df):
    """
    Komplett transform-pipeline för orderdata.
    """
    print("Startar transform...")

    df_clean = df.copy()

    df_clean = clean_categories(df_clean)
    df_clean = clean_channel(df_clean)
    df_clean = clean_status(df_clean)
    df_clean = clean_order_price(df_clean)
    df_clean = clean_date(df_clean)

    df_clean = add_order_total(df_clean)    
    df_clean = add_time_features(df_clean)

    print("Transform klar!")

    return df_clean

In [89]:
df_clean = transform_orders(df_raw)

df_clean.head()

Startar transform...
Transform klar!

,order_id,kund_id,order_datum,produkt,kategori,antal,pris_st,kanal,status,order_total,order_month,order_day
0,ORD-001,K001,2024-01-15,Espresso Blend,kaffe,2,189.0,online,levererad,378.0,1,Monday
1,ORD-002,K003,2024-01-16,Lungo Klassisk,kaffe,1,169.0,butik,levererad,169.0,1,Tuesday
2,ORD-003,K002,2024-01-17,Cappuccino Mix,kaffe,3,199.0,online,levererad,597.0,1,Wednesday
3,ORD-004,K005,2024-01-18,Kaffekvarn Pro,tillbehör,1,899.0,online,levererad,899.0,1,Thursday
4,ORD-005,K001,2024-01-20,Espresso Blend,kaffe,1,189.0,butik,levererad,189.0,1,Saturday

In [81]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     40 non-null     str
 1   kund_id      40 non-null     str
 2   order_datum  40 non-null     datetime64[us]
 3   produkt      40 non-null     str
 4   kategori     40 non-null     str
 5   antal        40 non-null     int64
 6   pris_st      40 non-null     float64
 7   kanal        40 non-null     str
 8   status       40 non-null     str
 9   order_total  40 non-null     float64
 10  order_month  40 non-null     int32
 11  order_day    40 non-null     str
dtypes: datetime64[us](1), float64(2), int32(1), int64(1), str(7)
memory usage: 3.7 KB

In [80]:
import sqlite3


conn = sqlite3.connect("nordkaffe.db")

In [90]:
df_clean.to_sql("orders", conn, if_exists="append", index=False)

40

In [91]:
df = pd.read_sql("SELECT * FROM orders", conn)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     120 non-null    str
 1   kund_id      120 non-null    str
 2   order_datum  120 non-null    str
 3   produkt      120 non-null    str
 4   kategori     120 non-null    str
 5   antal        120 non-null    int64
 6   pris_st      120 non-null    float64
 7   kanal        120 non-null    str
 8   status       120 non-null    str
 9   order_total  120 non-null    float64
 10  order_month  120 non-null    int64
 11  order_day    120 non-null    str
dtypes: float64(2), int64(2), str(8)
memory usage: 11.4 KB