In [1]:
!pip install pandas numpy

Collecting pandas
  Downloading pandas-3.0.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting numpy
  Downloading numpy-2.4.1-cp313-cp313-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.0-cp313-cp313-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 547.8 kB/s  0:00:17m0:00:0100:01
Downloading numpy-2.4.1-cp313-cp313-macosx_14_0_arm64.whl (5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 587.0 kB/s  0:00:08 eta 0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.4.1 pandas-3.0.0

In [2]:
import pandas as pd
import numpy as np

In [24]:
df = pd.read_csv('datasets/nordkaffe_kunder_dirty.csv')
df.head()

,kund_id,namn,email,stad,registrerad,total_kop,medlemsniva
0,K001,Anna Andersson,anna.andersson@gmail.com,Stockholm,2023-01-15,2450.50,Guld
1,K002,Erik Eriksson,erik.eriksson@hotmail.com,Göteborg,2023-02-20,1230,Silver
2,K003,Maria Svensson,maria.svensson@yahoo.se,malmö,15/03/2023,3200.00,Guld
3,K004,Johan Karlsson,johan.karlsson@gmail.com,Stockholm,2023-04-10,890.5,brons
4,K005,Lisa Nilsson,lisa.nilsson@outlook.com,UPPSALA,2023-05-05,1560,Silver

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   kund_id      30 non-null     str
 1   namn         29 non-null     str
 2   email        28 non-null     str
 3   stad         30 non-null     str
 4   registrerad  29 non-null     str
 5   total_kop    29 non-null     str
 6   medlemsniva  30 non-null     str
dtypes: str(7)
memory usage: 1.8 KB

In [39]:
df

,kund_id,namn,email,stad,registrerad,total_kop,medlemsniva
0,K001,Anna Andersson,anna.andersson@gmail.com,stockholm,2023-01-15,2450.50,guld
1,K002,Erik Eriksson,erik.eriksson@hotmail.com,göteborg,2023-02-20,1230,silver
2,K003,Maria Svensson,maria.svensson@yahoo.se,malmö,2023-03-15,3200.00,guld
3,K004,Johan Karlsson,johan.karlsson@gmail.com,stockholm,2023-10-04,890.5,brons
4,K005,Lisa Nilsson,lisa.nilsson@outlook.com,uppsala,2023-05-05,1560,silver
5,K006,Peter Lindgren,NaN,göteborg,2023-12-06,2100.00,silver
6,K007,Sara Bergström,sara.bergstrom@gmail.com,stockholm,2023-07-22,450,brons
7,K008,Anders Johansson,anders.j@hotmail.com,göteborg,2023-08-30,3650.50,guld
8,K009,Emma Larsson,emma.larsson@gmail.com,malmö,2023-09-15,1890,silver
9,K010,Oscar Pettersson,oscar.p@yahoo.se,stockholm,2023-01-10,670.00,brons
10,K011,Karin Olsson,karin.olsson@gmail.com,uppsala,2023-11-18,2890,guld
11,K012,Fredrik Lindqvist,fredrik@lindqvist.se,malmö,2023-05-12,1 450,silver
12,K013,Helena Ström,helena.strom@hotmail.com,göteborg,2024-10-01,520.50,brons
13,K014,Mikael Berg,mikael.berg@gmail.com,stockholm,2024-02-10,4200.00,guld
14,K015,Sofie Nyström,sofie.n@outlook.com,malmö,2024-03-15,980,silver
15,K016,David Ekberg,david.ekberg@gmail.com,uppsala,2024-04-20,1670.50,silver
16,K017,Anna Andersson,anna.a@yahoo.se,göteborg,2024-05-25,2340,guld
17,K018,Marcus Holm,marcus.holm@gmail.com,stockholm,2024-08-06,1120,silver
18,K019,Elin Fransson,elin.f@hotmail.com,malmö,2024-07-14,3100.00,guld
19,K020,Gustav Lund,gustav.lund@gmail.com,göteborg,NaT,1890.50,silver
20,K021,Ida Månsson,NaN,uppsala,2024-01-09,2 250,guld
21,K022,Jakob Persson,jakob.p@outlook.com,stockholm,2024-10-10,430,brons
22,K023,Malin Dahl,malin.dahl@gmail.com,malmö,2024-11-15,1560.00,silver
23,K024,Niklas Åberg,niklas.aberg@hotmail.com,göteborg,2024-01-12,2780,guld
24,K025,Olivia Sandberg,olivia.s@gmail.com,uppsala,2024-12-20,890.50,brons
25,K026,NaN,tom.karlsson@yahoo.se,stockholm,2025-05-01,1340,silver
26,K027,Viktor Sjögren,viktor.sjogren@gmail.com,malmö,2025-01-15,NaN,brons
27,K028,Wilma Lindberg,wilma.l@hotmail.com,göteborg,2025-10-02,2100.00,guld
28,K029,Axel Nordin,axel.nordin@outlook.com,uppsala,2025-01-03,1670,silver
29,K030,Beatrice Ek,beatrice.ek@gmail.com,stockholm,2025-03-20,3450.50,guld

In [27]:
df["stad"].value_counts()

stad
Stockholm        7
Göteborg         5
Uppsala          5
Malmö            3
  Göteborg       2
malmö            2
UPPSALA          1
göteborg         1
  stockholm      1
MALMÖ            1
stockholm        1
  malmö          1
Name: count, dtype: int64

In [28]:
df["medlemsniva"].value_counts()

medlemsniva
Silver    9
Guld      8
Brons     5
brons     2
silver    2
GULD      2
SILVER    1
guld      1
Name: count, dtype: int64

In [29]:
df.isnull().sum()

kund_id        0
namn           1
email          2
stad           0
registrerad    1
total_kop      1
medlemsniva    0
dtype: int64

In [30]:
df["namn"].nunique()

28

In [31]:
df["stad"] = df["stad"].str.strip().str.lower()

In [32]:
df["stad"].value_counts()

stad
stockholm    9
göteborg     8
malmö        7
uppsala      6
Name: count, dtype: int64

In [33]:
df["medlemsniva"] = df["medlemsniva"].str.strip().str.lower()

In [34]:
df["medlemsniva"].value_counts()

medlemsniva
silver    12
guld      11
brons      7
Name: count, dtype: int64

In [ ]:
df["registrerad"] = pd.to_datetime(df["registrerad"], dayfirst=True, errors="coerce", format="mixed")

In [36]:
df["registrerad"].head()

0   2023-01-15
1   2023-02-20
2   2023-03-15
3   2023-10-04
4   2023-05-05
Name: registrerad, dtype: datetime64[us]

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   kund_id      30 non-null     str
 1   namn         29 non-null     str
 2   email        28 non-null     str
 3   stad         30 non-null     str
 4   registrerad  29 non-null     datetime64[us]
 5   total_kop    29 non-null     str
 6   medlemsniva  30 non-null     str
dtypes: datetime64[us](1), str(6)
memory usage: 1.8 KB

In [ ]:
df["total_kop"].isnull()

np.int64(1)

In [ ]:
df["total_kop"] = df["total_kop"].str.replace(" ", "")

df["total_kop"] = pd.to_numeric(df["total_kop"], errors="coerce")

:

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   kund_id      30 non-null     str
 1   namn         29 non-null     str
 2   email        28 non-null     str
 3   stad         30 non-null     str
 4   registrerad  29 non-null     datetime64[us]
 5   total_kop    29 non-null     float64
 6   medlemsniva  30 non-null     str
dtypes: datetime64[us](1), float64(1), str(5)
memory usage: 1.8 KB

In [ ]:
median = df["total_kop"].median()

df["total_kop"] = df["total_kop"].fillna(median)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   kund_id      30 non-null     str
 1   namn         29 non-null     str
 2   email        28 non-null     str
 3   stad         30 non-null     str
 4   registrerad  29 non-null     datetime64[us]
 5   total_kop    30 non-null     float64
 6   medlemsniva  30 non-null     str
dtypes: datetime64[us](1), float64(1), str(5)
memory usage: 1.8 KB

In [ ]:
df["namn"] = df["namn"].fillna("Okänd")


df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   kund_id      30 non-null     str
 1   namn         30 non-null     str
 2   email        28 non-null     str
 3   stad         30 non-null     str
 4   registrerad  29 non-null     datetime64[us]
 5   total_kop    30 non-null     float64
 6   medlemsniva  30 non-null     str
dtypes: datetime64[us](1), float64(1), str(5)
memory usage: 1.8 KB

In [59]:
df.groupby("medlemsniva")["total_kop"].agg(["mean", "median", "min", "max"])

                    mean  median     min     max
medlemsniva
brons         788.857143   670.0   430.0  1670.5
guld         2946.500000  2890.0  2100.0  4200.0
silver       1538.416667  1560.0   980.0  2100.0

In [ ]:
hogvarde_kunder = df[df["total_kop"] > 2000]

'namn'

In [70]:
hogvarde_kunder

,namn,namn,email,stad,registrerad,total_kop,medlemsniva
0,K001,Anna Andersson,anna.andersson@gmail.com,stockholm,2023-01-15,2450.5,guld
2,K003,Maria Svensson,maria.svensson@yahoo.se,malmö,2023-03-15,3200.0,guld
5,K006,Peter Lindgren,NaN,göteborg,2023-12-06,2100.0,silver
7,K008,Anders Johansson,anders.j@hotmail.com,göteborg,2023-08-30,3650.5,guld
10,K011,Karin Olsson,karin.olsson@gmail.com,uppsala,2023-11-18,2890.0,guld
13,K014,Mikael Berg,mikael.berg@gmail.com,stockholm,2024-02-10,4200.0,guld
16,K017,Anna Andersson,anna.a@yahoo.se,göteborg,2024-05-25,2340.0,guld
18,K019,Elin Fransson,elin.f@hotmail.com,malmö,2024-07-14,3100.0,guld
20,K021,Ida Månsson,NaN,uppsala,2024-01-09,2250.0,guld
23,K024,Niklas Åberg,niklas.aberg@hotmail.com,göteborg,2024-01-12,2780.0,guld
27,K028,Wilma Lindberg,wilma.l@hotmail.com,göteborg,2025-10-02,2100.0,guld
29,K030,Beatrice Ek,beatrice.ek@gmail.com,stockholm,2025-03-20,3450.5,guld

In [83]:
df['year'] = df['registrerad'].dt.year
df['month'] = df['registrerad'].dt.month
df["day"] = df["registrerad"].dt.day_name()
df["day"]

0        Sunday
1        Monday
2     Wednesday
3     Wednesday
4        Friday
5     Wednesday
6      Saturday
7     Wednesday
8        Friday
9       Tuesday
10     Saturday
11       Friday
12      Tuesday
13     Saturday
14       Friday
15     Saturday
16     Saturday
17      Tuesday
18       Sunday
19          NaN
20      Tuesday
21     Thursday
22       Friday
23       Friday
24       Friday
25     Thursday
26    Wednesday
27     Thursday
28       Friday
29     Thursday
Name: day, dtype: str

In [ ]:
from datetime import datetime
df['days_as_customer'] = (datetime.now() - df['registrerad']).dt.days

In [85]:
stad_dummies = pd.get_dummies(df["stad"], prefix="stad")

stad_dummies.head()

   stad_göteborg  stad_malmö  stad_stockholm  stad_uppsala
0          False       False            True         False
1           True       False           False         False
2          False        True           False         False
3          False       False            True         False
4          False       False           False          True

In [86]:
medlemsniva_dummies = pd.get_dummies(df["medlemsniva"], prefix="medlemsniva")
medlemsniva_dummies.head()

   medlemsniva_brons  medlemsniva_guld  medlemsniva_silver
0              False              True               False
1              False             False                True
2              False              True               False
3               True             False               False
4              False             False                True

In [88]:
df_feat = pd.concat([df, stad_dummies, medlemsniva_dummies], axis=1)
df_feat.drop(columns=["stad", "medlemsniva"], inplace=True)

In [91]:
df_feat.head()

,namn,namn,email,registrerad,total_kop,year,month,days_as_customer,day,stad_göteborg,stad_malmö,stad_stockholm,stad_uppsala,medlemsniva_brons,medlemsniva_guld,medlemsniva_silver
0,K001,Anna Andersson,anna.andersson@gmail.com,2023-01-15,2450.5,2023.0,1.0,1103.0,Sunday,False,False,True,False,False,True,False
1,K002,Erik Eriksson,erik.eriksson@hotmail.com,2023-02-20,1230.0,2023.0,2.0,1067.0,Monday,True,False,False,False,False,False,True
2,K003,Maria Svensson,maria.svensson@yahoo.se,2023-03-15,3200.0,2023.0,3.0,1044.0,Wednesday,False,True,False,False,False,True,False
3,K004,Johan Karlsson,johan.karlsson@gmail.com,2023-10-04,890.5,2023.0,10.0,841.0,Wednesday,False,False,True,False,True,False,False
4,K005,Lisa Nilsson,lisa.nilsson@outlook.com,2023-05-05,1560.0,2023.0,5.0,993.0,Friday,False,False,False,True,False,False,True

In [93]:
df.groupby("month")["total_kop"].agg(["mean", "median", "min", "max"])

              mean   median     min     max
month
1.0    1915.166667  1960.25   670.0  2780.0
2.0    2715.000000  2715.00  1230.0  4200.0
3.0    2543.500000  3200.00   980.0  3450.5
4.0    1670.500000  1670.50  1670.5  1670.5
5.0    1672.500000  1505.00  1340.0  2340.0
7.0    1775.000000  1775.00   450.0  3100.0
8.0    2385.250000  2385.25  1120.0  3650.5
9.0    1890.000000  1890.00  1890.0  1890.0
10.0    985.250000   705.50   430.0  2100.0
11.0   2225.000000  2225.00  1560.0  2890.0
12.0   1495.250000  1495.25   890.5  2100.0

In [94]:
## Analys med One-Hot Encoded Features

Nu när vi har skapat one-hot encoded features kan vi göra djupare analyser.

:

In [95]:
# Korrelationsanalys: Hur korrelerar one-hot features med total_kop?
# Välj bara numeriska kolumner för korrelationsberäkning

numeric_cols = df_feat.select_dtypes(include=[np.number]).columns
correlation_with_total_kop = df_feat[numeric_cols].corr()["total_kop"].sort_values(ascending=False)
print("Korrelation med total_kop:\n")
print(correlation_with_total_kop)

Korrelation med total_kop:

total_kop           1.000000
days_as_customer    0.049090
year                0.045465
month              -0.236891
Name: total_kop, dtype: float64

In [96]:
# Filtrera ut bara stad och medlemsnivå-features för tydligare bild
stad_cols = [col for col in df_feat.columns if col.startswith("stad_")]
medlems_cols = [col for col in df_feat.columns if col.startswith("medlemsniva_")]

print("=" * 50)
print("STAD-FEATURES KORRELATION MED TOTAL_KÖP:")
print("=" * 50)
stad_corr = df_feat[stad_cols + ["total_kop"]].corr()["total_kop"].drop("total_kop").sort_values(ascending=False)
print(stad_corr)

print("\n" + "=" * 50)
print("MEDLEMSNIVÅ-FEATURES KORRELATION MED TOTAL_KÖP:")
print("=" * 50)
medlems_corr = df_feat[medlems_cols + ["total_kop"]].corr()["total_kop"].drop("total_kop").sort_values(ascending=False)
print(medlems_corr)

==================================================
STAD-FEATURES KORRELATION MED TOTAL_KÖP:
==================================================
stad_göteborg     0.120893
stad_malmö        0.055590
stad_uppsala     -0.029560
stad_stockholm   -0.142166
Name: total_kop, dtype: float64

==================================================
MEDLEMSNIVÅ-FEATURES KORRELATION MED TOTAL_KÖP:
==================================================
medlemsniva_guld      0.827547
medlemsniva_silver   -0.284221
medlemsniva_brons    -0.613665
Name: total_kop, dtype: float64

In [97]:
# Genomsnittligt köpbelopp per stad (med one-hot encoding)
print("GENOMSNITTLIGT TOTAL_KÖP PER STAD:")
print("-" * 40)

for col in stad_cols:
    stad_namn = col.replace("stad_", "").title()
    avg_kop = df_feat[df_feat[col] == 1]["total_kop"].mean()
    antal = df_feat[df_feat[col] == 1].shape[0]
    print(f"{stad_namn:15} | Snitt: {avg_kop:,.0f} kr | Antal kunder: {antal}")

GENOMSNITTLIGT TOTAL_KÖP PER STAD:
----------------------------------------
Göteborg        | Snitt: 2,076 kr | Antal kunder: 8
Malmö           | Snitt: 1,979 kr | Antal kunder: 7
Stockholm       | Snitt: 1,667 kr | Antal kunder: 9
Uppsala         | Snitt: 1,822 kr | Antal kunder: 6

In [98]:
# Genomsnittligt köpbelopp per medlemsnivå (med one-hot encoding)
print("GENOMSNITTLIGT TOTAL_KÖP PER MEDLEMSNIVÅ:")
print("-" * 40)

for col in medlems_cols:
    niva_namn = col.replace("medlemsniva_", "").title()
    avg_kop = df_feat[df_feat[col] == 1]["total_kop"].mean()
    median_kop = df_feat[df_feat[col] == 1]["total_kop"].median()
    antal = df_feat[df_feat[col] == 1].shape[0]
    print(f"{niva_namn:10} | Snitt: {avg_kop:,.0f} kr | Median: {median_kop:,.0f} kr | Antal: {antal}")

GENOMSNITTLIGT TOTAL_KÖP PER MEDLEMSNIVÅ:
----------------------------------------
Brons      | Snitt: 789 kr | Median: 670 kr | Antal: 7
Guld       | Snitt: 2,946 kr | Median: 2,890 kr | Antal: 11
Silver     | Snitt: 1,538 kr | Median: 1,560 kr | Antal: 12

In [99]:
# Skapa en sammanfattningstabell med aggregerade statistik per one-hot feature
def analyze_one_hot_features(df, feature_cols, target_col):
    """Analyserar one-hot encoded features mot en målvariabel"""
    results = []
    
    for col in feature_cols:
        grupp = df[df[col] == 1][target_col]
        results.append({
            "feature": col,
            "antal": grupp.count(),
            "medel": grupp.mean(),
            "median": grupp.median(),
            "std": grupp.std(),
            "min": grupp.min(),
            "max": grupp.max()
        })
    
    return pd.DataFrame(results).sort_values("medel", ascending=False)

# Analysera stad-features
print("DETALJERAD ANALYS - STAD FEATURES:")
stad_analysis = analyze_one_hot_features(df_feat, stad_cols, "total_kop")
stad_analysis

DETALJERAD ANALYS - STAD FEATURES:

          feature  antal        medel   median          std    min     max
0   stad_göteborg      8  2076.437500  2100.00   942.278335  520.5  3650.5
1      stad_malmö      7  1978.642857  1670.50   846.953103  980.0  3200.0
3    stad_uppsala      6  1821.833333  1670.25   679.146572  890.5  2890.0
2  stad_stockholm      9  1666.833333  1120.00  1379.546597  430.0  4200.0

In [100]:
# Analysera medlemsnivå-features
print("DETALJERAD ANALYS - MEDLEMSNIVÅ FEATURES:")
medlems_analysis = analyze_one_hot_features(df_feat, medlems_cols, "total_kop")
medlems_analysis

DETALJERAD ANALYS - MEDLEMSNIVÅ FEATURES:

              feature  antal        medel  median         std     min     max
1    medlemsniva_guld     11  2946.500000  2890.0  652.316334  2100.0  4200.0
2  medlemsniva_silver     12  1538.416667  1560.0  334.099933   980.0  2100.0
0   medlemsniva_brons      7   788.857143   670.0  433.532363   430.0  1670.5

In [101]:
# Korsanalys: Stad x Medlemsnivå - Antal kunder i varje kombination
# Använder originaldata för korsanalys
print("KORSANALYS: ANTAL KUNDER PER STAD OCH MEDLEMSNIVÅ")
print("=" * 60)

cross_tab = pd.crosstab(df["stad"], df["medlemsniva"], margins=True, margins_name="Totalt")
cross_tab

KORSANALYS: ANTAL KUNDER PER STAD OCH MEDLEMSNIVÅ
============================================================

medlemsniva  brons  guld  silver  Totalt
stad
göteborg         1     4       3       8
malmö            1     2       4       7
stockholm        4     3       2       9
uppsala          1     2       3       6
Totalt           7    11      12      30

In [102]:
# Pivot-tabell: Genomsnittligt köpbelopp per Stad x Medlemsnivå
print("GENOMSNITTLIGT KÖPBELOPP PER STAD OCH MEDLEMSNIVÅ")
print("=" * 60)

pivot_avg = df.pivot_table(
    values="total_kop", 
    index="stad", 
    columns="medlemsniva", 
    aggfunc="mean"
).round(0)

pivot_avg

GENOMSNITTLIGT KÖPBELOPP PER STAD OCH MEDLEMSNIVÅ
============================================================

medlemsniva   brons    guld  silver
stad
göteborg      520.0  2718.0  1740.0
malmö        1670.0  3150.0  1470.0
stockholm     610.0  3367.0  1230.0
uppsala       890.0  2570.0  1634.0

In [103]:
# Identifiera bästa kombinationer baserat på one-hot features
print("TOP KOMBINATIONER - STAD + MEDLEMSNIVÅ MED HÖGST GENOMSNITTLIGT KÖP")
print("=" * 70)

# Skapa kombinationsanalys
combo_analysis = df.groupby(["stad", "medlemsniva"]).agg({
    "total_kop": ["mean", "sum", "count"]
}).round(0)

combo_analysis.columns = ["Snitt_kop", "Total_kop", "Antal_kunder"]
combo_analysis = combo_analysis.sort_values("Snitt_kop", ascending=False)
combo_analysis

TOP KOMBINATIONER - STAD + MEDLEMSNIVÅ MED HÖGST GENOMSNITTLIGT KÖP
======================================================================

                       Snitt_kop  Total_kop  Antal_kunder
stad      medlemsniva
stockholm guld            3367.0    10101.0             3
malmö     guld            3150.0     6300.0             2
göteborg  guld            2718.0    10870.0             4
uppsala   guld            2570.0     5140.0             2
göteborg  silver          1740.0     5220.0             3
malmö     brons           1670.0     1670.0             1
uppsala   silver          1634.0     4900.0             3
malmö     silver          1470.0     5880.0             4
stockholm silver          1230.0     2460.0             2
uppsala   brons            890.0      890.0             1
stockholm brons            610.0     2440.0             4
göteborg  brons            520.0      520.0             1

In [104]:
# Feature Importance Analys (baserat på korrelationsstyrka)
# Skapar en "feature importance"-liknande ranking

all_one_hot_cols = stad_cols + medlems_cols
feature_importance = df_feat[all_one_hot_cols + ["total_kop"]].corr()["total_kop"].drop("total_kop")

# Skapa en DataFrame med absolut korrelation för ranking
importance_df = pd.DataFrame({
    "feature": feature_importance.index,
    "korrelation": feature_importance.values,
    "abs_korrelation": np.abs(feature_importance.values)
}).sort_values("abs_korrelation", ascending=False)

print("FEATURE IMPORTANCE RANKING (baserat på korrelation med total_kop)")
print("=" * 70)
print("\nPositiv korrelation = köper MER")
print("Negativ korrelation = köper MINDRE")
print("-" * 70)
importance_df

FEATURE IMPORTANCE RANKING (baserat på korrelation med total_kop)
======================================================================

Positiv korrelation = köper MER
Negativ korrelation = köper MINDRE
----------------------------------------------------------------------

              feature  korrelation  abs_korrelation
5    medlemsniva_guld     0.827547         0.827547
4   medlemsniva_brons    -0.613665         0.613665
6  medlemsniva_silver    -0.284221         0.284221
2      stad_stockholm    -0.142166         0.142166
0       stad_göteborg     0.120893         0.120893
1          stad_malmö     0.055590         0.055590
3        stad_uppsala    -0.029560         0.029560